name = "rapid-king-78e4"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "KV"
id = "86bcc919b18d482098c83e8d8117f712"

# 每5分钟自动抓一次（免费版安全范围内）
# 每10分钟改成：*/10 * * * *
[triggers]
crons = ["*/5 * * * *"]
